name: my_workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    workflow_dispatch:

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "testing"
        shell: bash

  job_2:
    runs-on: ubuntu-latest
    steps:
      - name: test2
        run: echo "testin 2"
        shell: bash