name: my_first_job
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: job1
        run: echo "hello world" > text.txt
    
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: job2
        run: echo "xd"